services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}/umami
      APP_SECRET: ${UMAMI_APP_SECRET}
      ALLOWED_FRAME_URLS: ${ALLOWED_FRAME_URLS}
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    networks:
      - gallery-network
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000/api/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-proxy:
    image: nginx:alpine
    container_name: umami-proxy
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - umami
    networks:
      - gallery-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: galleria
    ports:
      - "5433:5432"
    volumes:
      - ./src/db/data:/var/lib/postgresql/data
      - ./src/db/initdb/:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - gallery-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d galleria" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}/galleria
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}/galleria
    volumes:
      - ./public/sitedata:/app/public/sitedata
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - gallery-network

networks:
  gallery-network:
